spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/etl
    username: etl
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect